"""
Solver backend implementations for various formats.

Each backend takes a NetworkCompiler and produces an EncodingResult
in its specific format.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from itertools import combinations
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Set, Tuple

if TYPE_CHECKING:
    from .compiler import NetworkCompiler

from .types import SolverBackend, ConstraintType, EncodingResult, Variable, Constraint


class SolverBackendBase(ABC):
    """Base class for solver backends."""
    
    def __init__(self, compiler: 'NetworkCompiler'):
        self.compiler = compiler
    
    @abstractmethod
    def encode(self) -> EncodingResult:
        """Encode the network to this backend's format."""
        pass


class DimacsBackend(SolverBackendBase):
    """
    DIMACS CNF format encoder.
    
    The DIMACS CNF format is the standard input format for SAT solvers.
    Each variable is a positive integer, negation is indicated by negative integers.
    
    Format:
        c comment line
        p cnf <num_vars> <num_clauses>
        1 2 -3 0    <- clause: x1 ∨ x2 ∨ ¬x3
        -1 2 0      <- clause: ¬x1 ∨ x2
        ...
    
    For finite domains, we use indicator variables:
        cell X with domain {1,2,3} gets variables x_1, x_2, x_3
        - At least one: (x_1 ∨ x_2 ∨ x_3)
        - At most one: pairwise ¬x_i ∨ ¬x_j
    """
    
    def __init__(self, compiler: 'NetworkCompiler'):
        super().__init__(compiler)
        self.clauses: List[List[int]] = []
        self.comments: List[str] = []
    
    def encode(self) -> EncodingResult:
        """Encode the network to DIMACS CNF format."""
        self.clauses = []
        self.comments = [
            f"c Problem: {self.compiler.name}",
            f"c Generated by propagator solver_export",
            "c"
        ]
        
        # Add variable comments
        self.comments.append("c Variable mapping:")
        for cell, var in self.compiler.variables.items():
            if var.domain:
                for value in var.domain:
                    sat_var = self.compiler._sat_var_map.get((cell, value))
                    if sat_var:
                        self.comments.append(f"c   {sat_var} = {var.name}={value}")
        self.comments.append("c")
        
        # Encode all constraints
        for constraint in self.compiler.constraints:
            self._encode_constraint(constraint)
        
        # Encode learned clauses
        for clause in self.compiler.learned_clauses:
            self._encode_raw_clause(clause)
        
        # Build DIMACS content
        num_vars = self.compiler._sat_var_counter
        num_clauses = len(self.clauses)
        
        lines = self.comments + [
            f"p cnf {num_vars} {num_clauses}"
        ]
        
        for clause in self.clauses:
            lines.append(" ".join(map(str, clause)) + " 0")
        
        content = "\n".join(lines)
        
        return EncodingResult(
            backend=SolverBackend.DIMACS_CNF,
            content=content,
            var_count=num_vars,
            clause_count=num_clauses,
            variable_map=dict(self.compiler._sat_decode_map),
            metadata={
                "format": "DIMACS CNF",
                "variables": {var.name: var.domain for var in self.compiler.variables.values()},
            }
        )
    
    def _get_var(self, cell: Any, value: Any) -> int:
        """Get SAT variable for (cell, value)."""
        return self.compiler._get_sat_var(cell, value)
    
    def _encode_constraint(self, constraint: 'Constraint') -> None:
        """Encode a single constraint to clauses."""
        ctype = constraint.constraint_type
        vars = constraint.variables
        params = constraint.params
        
        if ctype == ConstraintType.DOMAIN:
            self._encode_domain(vars[0], params["domain"])
        
        elif ctype == ConstraintType.ALL_DISTINCT:
            self._encode_all_distinct(vars)
        
        elif ctype == ConstraintType.INEQUALITY:
            self._encode_inequality(vars[0], vars[1])
        
        elif ctype == ConstraintType.EQUALITY:
            self._encode_equality(vars[0], vars[1])
        
        elif ctype == ConstraintType.LESS_THAN:
            self._encode_less_than(vars[0], vars[1])
        
        elif ctype == ConstraintType.LESS_EQUAL:
            self._encode_less_equal(vars[0], vars[1])
        
        elif ctype == ConstraintType.GREATER_THAN:
            self._encode_less_than(vars[1], vars[0])  # x > y == y < x
        
        elif ctype == ConstraintType.GREATER_EQUAL:
            self._encode_less_equal(vars[1], vars[0])  # x >= y == y <= x
        
        elif ctype == ConstraintType.FIXED_VALUE:
            self._encode_fixed_value(vars[0], params["value"])
        
        elif ctype == ConstraintType.EXACTLY_ONE:
            self._encode_exactly_one_boolean(vars)
        
        elif ctype == ConstraintType.AT_MOST_ONE:
            self._encode_at_most_one_boolean(vars)
        
        elif ctype == ConstraintType.AT_LEAST_ONE:
            self._encode_at_least_one_boolean(vars)
        
        elif ctype == ConstraintType.IMPLIES:
            self._encode_implies(vars[0], vars[1])
        
        elif ctype == ConstraintType.OR:
            self._encode_or(vars)
        
        elif ctype == ConstraintType.AND:
            self._encode_and(vars)
        
        elif ctype == ConstraintType.LINEAR_SUM:
            self._encode_linear_sum(vars, params)
        
        elif ctype == ConstraintType.PRODUCT:
            self._encode_product(vars[0], vars[1], vars[2])

        elif ctype == ConstraintType.ABSOLUTE_VALUE:
            self._encode_absolute_value(vars[0], vars[1])
        
        else:
            raise ValueError(f"Unsupported constraint type for DIMACS: {ctype}")
    
    def _encode_domain(self, var: 'Variable', domain: List[Any]) -> None:
        """
        Encode finite domain constraint: exactly one value from domain.
        
        ALO (At Least One): x_1 ∨ x_2 ∨ ... ∨ x_n
        AMO (At Most One): ∀i<j: ¬x_i ∨ ¬x_j
        """
        sat_vars = [self._get_var(var.cell, v) for v in domain]
        
        # At least one
        self.clauses.append(sat_vars)
        
        # At most one (pairwise)
        for v1, v2 in combinations(sat_vars, 2):
            self.clauses.append([-v1, -v2])
    
    def _encode_all_distinct(self, vars: List['Variable']) -> None:
        """
        Encode all_distinct constraint.
        
        For each pair of variables and each value:
        ¬(x=v) ∨ ¬(y=v)
        """
        for v1, v2 in combinations(vars, 2):
            self._encode_inequality(v1, v2)
    
    def _encode_inequality(self, var1: 'Variable', var2: 'Variable') -> None:
        """
        Encode var1 ≠ var2.
        
        For each value v in the intersection of domains:
        ¬(var1=v) ∨ ¬(var2=v)
        """
        if var1.domain is None or var2.domain is None:
            raise ValueError("Cannot encode inequality without finite domains")
        
        common_values = set(var1.domain) & set(var2.domain)
        for value in common_values:
            v1 = self._get_var(var1.cell, value)
            v2 = self._get_var(var2.cell, value)
            self.clauses.append([-v1, -v2])
    
    def _encode_equality(self, var1: 'Variable', var2: 'Variable') -> None:
        """
        Encode var1 = var2.
        
        For each value v:
        (var1=v) => (var2=v) and (var2=v) => (var1=v)
        Which gives: (¬var1=v ∨ var2=v) ∧ (var1=v ∨ ¬var2=v)
        """
        if var1.domain is None or var2.domain is None:
            raise ValueError("Cannot encode equality without finite domains")
        
        common_values = set(var1.domain) & set(var2.domain)
        for value in common_values:
            v1 = self._get_var(var1.cell, value)
            v2 = self._get_var(var2.cell, value)
            self.clauses.append([-v1, v2])  # v1 => v2
            self.clauses.append([v1, -v2])  # v2 => v1
    
    def _encode_less_than(self, var1: 'Variable', var2: 'Variable') -> None:
        """
        Encode var1 < var2.
        
        For each pair (v1, v2) where v1 >= v2:
        ¬(var1=v1) ∨ ¬(var2=v2)
        """
        if var1.domain is None or var2.domain is None:
            raise ValueError("Cannot encode less_than without finite domains")
        
        for val1 in var1.domain:
            for val2 in var2.domain:
                if val1 >= val2:  # Forbidden combination
                    sv1 = self._get_var(var1.cell, val1)
                    sv2 = self._get_var(var2.cell, val2)
                    self.clauses.append([-sv1, -sv2])
    
    def _encode_less_equal(self, var1: 'Variable', var2: 'Variable') -> None:
        """
        Encode var1 <= var2.
        
        For each pair (v1, v2) where v1 > v2:
        ¬(var1=v1) ∨ ¬(var2=v2)
        """
        if var1.domain is None or var2.domain is None:
            raise ValueError("Cannot encode less_equal without finite domains")
        
        for val1 in var1.domain:
            for val2 in var2.domain:
                if val1 > val2:  # Forbidden combination
                    sv1 = self._get_var(var1.cell, val1)
                    sv2 = self._get_var(var2.cell, val2)
                    self.clauses.append([-sv1, -sv2])
    
    def _encode_fixed_value(self, var: 'Variable', value: Any) -> None:
        """Encode var = value (unit clause)."""
        sat_var = self._get_var(var.cell, value)
        self.clauses.append([sat_var])
    
    def _encode_exactly_one_boolean(self, vars: List['Variable']) -> None:
        """Exactly one boolean variable is true."""
        # For boolean vars, domain is [True, False]
        true_vars = [self._get_var(v.cell, True) for v in vars]
        
        # At least one
        self.clauses.append(true_vars)
        
        # At most one
        for v1, v2 in combinations(true_vars, 2):
            self.clauses.append([-v1, -v2])
    
    def _encode_at_most_one_boolean(self, vars: List['Variable']) -> None:
        """At most one boolean variable is true."""
        true_vars = [self._get_var(v.cell, True) for v in vars]
        for v1, v2 in combinations(true_vars, 2):
            self.clauses.append([-v1, -v2])
    
    def _encode_at_least_one_boolean(self, vars: List['Variable']) -> None:
        """At least one boolean variable is true."""
        true_vars = [self._get_var(v.cell, True) for v in vars]
        self.clauses.append(true_vars)
    
    def _encode_implies(self, antecedent: 'Variable', consequent: 'Variable') -> None:
        """Encode antecedent => consequent for boolean vars."""
        ant_true = self._get_var(antecedent.cell, True)
        con_true = self._get_var(consequent.cell, True)
        # p => q == ¬p ∨ q
        self.clauses.append([-ant_true, con_true])
    
    def _encode_or(self, vars: List['Variable']) -> None:
        """Encode disjunction for boolean vars."""
        true_vars = [self._get_var(v.cell, True) for v in vars]
        self.clauses.append(true_vars)
    
    def _encode_and(self, vars: List['Variable']) -> None:
        """Encode conjunction for boolean vars (each must be true)."""
        for v in vars:
            true_var = self._get_var(v.cell, True)
            self.clauses.append([true_var])
    
    def _encode_linear_sum(self, vars: List['Variable'], params: Dict) -> None:
        """
        Encode linear sum constraint.
        
        For finite domains, we enumerate all satisfying combinations.
        This is expensive but correct.
        """
        coeffs = params["coefficients"]
        total = params["total"]
        relation = params.get("relation", "=")
        
        # Get all domains
        domains = [v.domain for v in vars]
        if any(d is None for d in domains):
            raise ValueError("Cannot encode linear sum without finite domains")
        
        # Generate all combinations and filter
        from itertools import product as cartesian_product
        
        def satisfies(values):
            s = sum(c * v for c, v in zip(coeffs, values))
            if relation == "=":
                return s == total
            elif relation == "<=":
                return s <= total
            elif relation == "<":
                return s < total
            elif relation == ">=":
                return s >= total
            elif relation == ">":
                return s > total
            return False
        
        # Find all satisfying assignments
        satisfying = []
        for combo in cartesian_product(*domains):
            if satisfies(combo):
                satisfying.append(combo)
        
        if not satisfying:
            # No satisfying assignment - add empty clause (UNSAT)
            self.clauses.append([])
            return
        
        # Encode: at least one satisfying combination
        # This uses auxiliary variables or direct encoding
        # For simplicity, we use the direct (exponential) encoding
        # Better encodings exist (sequential counter, etc.)
        
        # Create disjunction of conjunctions
        # (x1=a1 ∧ x2=a2 ∧ ...) ∨ (x1=b1 ∧ x2=b2 ∧ ...) ∨ ...
        
        # We need to forbid all non-satisfying combinations
        for combo in cartesian_product(*domains):
            if not satisfies(combo):
                # Forbid this combination
                clause = []
                for v, val in zip(vars, combo):
                    clause.append(-self._get_var(v.cell, val))
                self.clauses.append(clause)
    
    def _encode_product(self, var1: 'Variable', var2: 'Variable', result: 'Variable') -> None:
        """
        Encode var1 * var2 = result.
        
        For finite domains, enumerate all valid (a, b, a*b) triples.
        """
        if any(v.domain is None for v in [var1, var2, result]):
            raise ValueError("Cannot encode product without finite domains")
        
        # For each (v1, v2, r) combination, if v1 * v2 != r, forbid it
        for v1 in var1.domain:
            for v2 in var2.domain:
                expected = v1 * v2
                for r in result.domain:
                    if r != expected:
                        # Forbid (var1=v1 ∧ var2=v2 ∧ result=r)
                        sv1 = self._get_var(var1.cell, v1)
                        sv2 = self._get_var(var2.cell, v2)
                        sr = self._get_var(result.cell, r)
                        self.clauses.append([-sv1, -sv2, -sr])

    def _encode_absolute_value(self, inp: 'Variable', out: 'Variable') -> None:
        """
        Encode |inp| = out.

        For finite domains, forbid all (inp=v, out=r) pairs where abs(v) != r.
        """
        if inp.domain is None or out.domain is None:
            raise ValueError("Cannot encode absolute value without finite domains")

        for in_val in inp.domain:
            for out_val in out.domain:
                if abs(in_val) != out_val:
                    sv_in = self._get_var(inp.cell, in_val)
                    sv_out = self._get_var(out.cell, out_val)
                    self.clauses.append([-sv_in, -sv_out])
    
    def _encode_raw_clause(self, clause: List[Tuple[Any, Any, bool]]) -> None:
        """Encode a raw clause from learned nogoods."""
        sat_clause = []
        for cell, value, positive in clause:
            sat_var = self._get_var(cell, value)
            if positive:
                sat_clause.append(sat_var)
            else:
                sat_clause.append(-sat_var)
        if sat_clause:
            self.clauses.append(sat_clause)


class SMTLib2Backend(SolverBackendBase):
    """
    SMT-LIB2 format encoder.
    
    SMT-LIB2 is the standard input format for SMT solvers (Z3, CVC5, Yices).
    It supports richer theories than pure SAT:
    - QF_LIA: Quantifier-free Linear Integer Arithmetic
    - QF_BV: Quantifier-free Bit Vectors
    - QF_UFLIA: With uninterpreted functions
    
    Example output:
        (set-logic QF_LIA)
        (declare-const x Int)
        (declare-const y Int)
        (assert (and (>= x 1) (<= x 5)))
        (assert (distinct x y))
        (check-sat)
        (get-model)
    """
    
    def __init__(self, compiler: 'NetworkCompiler', logic: str = "QF_LIA"):
        super().__init__(compiler)
        self.logic = logic
        self.declarations: List[str] = []
        self.assertions: List[str] = []
    
    def encode(self) -> EncodingResult:
        """Encode the network to SMT-LIB2 format."""
        self.declarations = []
        self.assertions = []
        
        # Declare all variables
        for var in self.compiler.variables.values():
            self._declare_variable(var)
        
        # Encode all constraints
        for constraint in self.compiler.constraints:
            self._encode_constraint(constraint)
        
        # Encode learned clauses
        for clause in self.compiler.learned_clauses:
            self._encode_raw_clause(clause)
        
        # Build SMT-LIB2 content
        lines = [
            f"; Problem: {self.compiler.name}",
            f"; Generated by propagator solver_export",
            "",
            f"(set-logic {self.logic})",
            ""
        ]
        
        lines.append("; Variable declarations")
        lines.extend(self.declarations)
        lines.append("")
        
        lines.append("; Constraints")
        lines.extend(self.assertions)
        lines.append("")
        
        lines.append("; Solve")
        lines.append("(check-sat)")
        lines.append("(get-model)")
        
        content = "\n".join(lines)
        
        return EncodingResult(
            backend=SolverBackend.SMT_LIB2,
            content=content,
            var_count=len(self.compiler.variables),
            clause_count=len(self.assertions),
            variable_map={v.name: v.cell for v in self.compiler.variables.values()},
            metadata={
                "format": "SMT-LIB2",
                "logic": self.logic,
                "variables": {v.name: v.domain for v in self.compiler.variables.values()},
            }
        )
    
    def _var_name(self, var: 'Variable') -> str:
        """Get SMT variable name."""
        return var.name

    @staticmethod
    def _smt_value(value: Any) -> str:
        """Render a Python literal as an SMT-LIB2 literal (bools are lowercase)."""
        if isinstance(value, bool):
            return "true" if value else "false"
        return str(value)

    def _declare_variable(self, var: 'Variable') -> None:
        """Declare a variable in SMT-LIB2."""
        name = self._var_name(var)
        
        if var.var_type == "boolean":
            self.declarations.append(f"(declare-const {name} Bool)")
        elif var.var_type in ("integer", "finite_domain"):
            if var.domain is None:
                # Domain-free integer variables are valid for SMT backends.
                self.declarations.append(f"(declare-const {name} Int)")
                return

            # Check if domain contains integers
            if var.domain and all(isinstance(v, int) for v in var.domain):
                self.declarations.append(f"(declare-const {name} Int)")
                
                # Add domain bounds
                min_val = min(var.domain)
                max_val = max(var.domain)
                self.assertions.append(f"(assert (and (>= {name} {min_val}) (<= {name} {max_val})))")
                
                # If domain has gaps, add explicit membership
                expected = set(range(min_val, max_val + 1))
                actual = set(var.domain)
                if expected != actual:
                    # Use explicit disjunction
                    values_smt = " ".join(f"(= {name} {v})" for v in var.domain)
                    self.assertions.append(f"(assert (or {values_smt}))")
            else:
                # Non-integer domain: encode as Int with explicit mapping
                # Map domain values to integers 0, 1, 2, ...
                self.declarations.append(f"(declare-const {name} Int)")
                domain_list = list(var.domain)
                self.assertions.append(f"(assert (and (>= {name} 0) (<= {name} {len(domain_list) - 1})))")
        else:
            # Default to Int
            self.declarations.append(f"(declare-const {name} Int)")
    
    def _encode_constraint(self, constraint: 'Constraint') -> None:
        """Encode a constraint to SMT-LIB2 assertions."""
        ctype = constraint.constraint_type
        vars = constraint.variables
        params = constraint.params
        
        if ctype == ConstraintType.DOMAIN:
            # Already handled in variable declaration
            pass
        
        elif ctype == ConstraintType.ALL_DISTINCT:
            names = " ".join(self._var_name(v) for v in vars)
            self.assertions.append(f"(assert (distinct {names}))")
        
        elif ctype == ConstraintType.INEQUALITY:
            n1, n2 = self._var_name(vars[0]), self._var_name(vars[1])
            self.assertions.append(f"(assert (distinct {n1} {n2}))")
        
        elif ctype == ConstraintType.EQUALITY:
            n1, n2 = self._var_name(vars[0]), self._var_name(vars[1])
            self.assertions.append(f"(assert (= {n1} {n2}))")
        
        elif ctype == ConstraintType.LESS_THAN:
            n1, n2 = self._var_name(vars[0]), self._var_name(vars[1])
            self.assertions.append(f"(assert (< {n1} {n2}))")
        
        elif ctype == ConstraintType.LESS_EQUAL:
            n1, n2 = self._var_name(vars[0]), self._var_name(vars[1])
            self.assertions.append(f"(assert (<= {n1} {n2}))")
        
        elif ctype == ConstraintType.GREATER_THAN:
            n1, n2 = self._var_name(vars[0]), self._var_name(vars[1])
            self.assertions.append(f"(assert (> {n1} {n2}))")
        
        elif ctype == ConstraintType.GREATER_EQUAL:
            n1, n2 = self._var_name(vars[0]), self._var_name(vars[1])
            self.assertions.append(f"(assert (>= {n1} {n2}))")
        
        elif ctype == ConstraintType.FIXED_VALUE:
            name = self._var_name(vars[0])
            value = self._smt_value(params["value"])
            self.assertions.append(f"(assert (= {name} {value}))")
        
        elif ctype == ConstraintType.LINEAR_SUM:
            self._encode_linear_sum(vars, params)
        
        elif ctype == ConstraintType.PRODUCT:
            n1 = self._var_name(vars[0])
            n2 = self._var_name(vars[1])
            result = self._var_name(vars[2])
            self.assertions.append(f"(assert (= (* {n1} {n2}) {result}))")

        elif ctype == ConstraintType.ABSOLUTE_VALUE:
            n1 = self._var_name(vars[0])
            result = self._var_name(vars[1])
            self.assertions.append(f"(assert (= (abs {n1}) {result}))")
        
        elif ctype == ConstraintType.EXACTLY_ONE:
            self._encode_exactly_one(vars)
        
        elif ctype == ConstraintType.AT_MOST_ONE:
            self._encode_at_most_one(vars)
        
        elif ctype == ConstraintType.AT_LEAST_ONE:
            names = " ".join(self._var_name(v) for v in vars)
            self.assertions.append(f"(assert (or {names}))")
        
        elif ctype == ConstraintType.IMPLIES:
            n1, n2 = self._var_name(vars[0]), self._var_name(vars[1])
            self.assertions.append(f"(assert (=> {n1} {n2}))")
        
        elif ctype == ConstraintType.OR:
            names = " ".join(self._var_name(v) for v in vars)
            self.assertions.append(f"(assert (or {names}))")
        
        elif ctype == ConstraintType.AND:
            names = " ".join(self._var_name(v) for v in vars)
            self.assertions.append(f"(assert (and {names}))")
        
        elif ctype == ConstraintType.NOT:
            name = self._var_name(vars[0])
            self.assertions.append(f"(assert (not {name}))")
        
        else:
            raise ValueError(f"Unsupported constraint type for SMT-LIB2: {ctype}")
    
    def _encode_linear_sum(self, vars: List['Variable'], params: Dict) -> None:
        """Encode linear sum constraint."""
        coeffs = params["coefficients"]
        total = params["total"]
        relation = params.get("relation", "=")
        
        # Build the sum expression
        terms = []
        for v, c in zip(vars, coeffs):
            name = self._var_name(v)
            if c == 1:
                terms.append(name)
            elif c == -1:
                terms.append(f"(- {name})")
            else:
                terms.append(f"(* {c} {name})")
        
        if len(terms) == 1:
            sum_expr = terms[0]
        else:
            sum_expr = "(+ " + " ".join(terms) + ")"
        
        # Map relation to SMT-LIB2 operator
        rel_map = {"=": "=", "<=": "<=", "<": "<", ">=": ">=", ">": ">"}
        rel_op = rel_map.get(relation, "=")
        
        self.assertions.append(f"(assert ({rel_op} {sum_expr} {total}))")
    
    def _encode_exactly_one(self, vars: List['Variable']) -> None:
        """Exactly one boolean variable is true."""
        names = [self._var_name(v) for v in vars]
        
        # At least one
        self.assertions.append(f"(assert (or {' '.join(names)}))")
        
        # At most one - pairwise
        for n1, n2 in combinations(names, 2):
            self.assertions.append(f"(assert (not (and {n1} {n2})))")
    
    def _encode_at_most_one(self, vars: List['Variable']) -> None:
        """At most one is true."""
        names = [self._var_name(v) for v in vars]
        for n1, n2 in combinations(names, 2):
            self.assertions.append(f"(assert (not (and {n1} {n2})))")
    
    def _encode_raw_clause(self, clause: List[Tuple[Any, Any, bool]]) -> None:
        """Encode a raw clause."""
        literals = []
        for cell, value, positive in clause:
            if cell in self.compiler.variables:
                name = self._var_name(self.compiler.variables[cell])
                value_smt = self._smt_value(value)
                if positive:
                    literals.append(f"(= {name} {value_smt})")
                else:
                    literals.append(f"(not (= {name} {value_smt}))")
        
        if literals:
            if len(literals) == 1:
                self.assertions.append(f"(assert {literals[0]})")
            else:
                self.assertions.append(f"(assert (or {' '.join(literals)}))")


# Optional Z3 Python backend (only if z3-solver is installed)
try:
    import z3
    
    class Z3Backend(SolverBackendBase):
        """
        Direct Z3 Python API backend.
        
        This provides direct integration with Z3 without needing file I/O.
        Requires: pip install z3-solver
        """
        
        def __init__(self, compiler: 'NetworkCompiler'):
            super().__init__(compiler)
            self.solver = z3.Solver()
            self.z3_vars: Dict[str, z3.ExprRef] = {}
        
        def encode(self) -> EncodingResult:
            """Encode and prepare Z3 solver."""
            self.solver = z3.Solver()
            self.z3_vars = {}
            
            # Create variables
            for var in self.compiler.variables.values():
                self._create_z3_var(var)
            
            # Add constraints
            for constraint in self.compiler.constraints:
                self._encode_constraint(constraint)
            
            # Add learned clauses
            for clause in self.compiler.learned_clauses:
                self._encode_raw_clause(clause)
            
            return EncodingResult(
                backend=SolverBackend.Z3_PYTHON,
                content=str(self.solver),
                var_count=len(self.z3_vars),
                clause_count=len(self.solver.assertions()),
                variable_map={name: self.compiler.variables[cell].cell 
                             for cell, var in self.compiler.variables.items()
                             for name in [var.name]},
                metadata={
                    "format": "Z3 Python API",
                    "solver": self.solver,
                    "z3_vars": self.z3_vars,
                }
            )
        
        def _create_z3_var(self, var: 'Variable') -> z3.ExprRef:
            """Create a Z3 variable."""
            if var.var_type == "boolean":
                z3_var = z3.Bool(var.name)
            else:
                z3_var = z3.Int(var.name)
                
                # Add domain constraints
                if var.domain:
                    min_val = min(var.domain)
                    max_val = max(var.domain)
                    self.solver.add(z3_var >= min_val)
                    self.solver.add(z3_var <= max_val)
                    
                    # Handle non-contiguous domains
                    expected = set(range(min_val, max_val + 1))
                    actual = set(var.domain)
                    if expected != actual:
                        self.solver.add(z3.Or([z3_var == v for v in var.domain]))
            
            self.z3_vars[var.name] = z3_var
            return z3_var
        
        def _get_z3_var(self, var: 'Variable') -> z3.ExprRef:
            """Get Z3 variable by Variable object."""
            return self.z3_vars[var.name]
        
        def _encode_constraint(self, constraint: 'Constraint') -> None:
            """Encode constraint using Z3 API."""
            ctype = constraint.constraint_type
            vars = constraint.variables
            params = constraint.params
            
            if ctype == ConstraintType.DOMAIN:
                pass  # Handled in variable creation
            
            elif ctype == ConstraintType.ALL_DISTINCT:
                z3_vars = [self._get_z3_var(v) for v in vars]
                self.solver.add(z3.Distinct(z3_vars))
            
            elif ctype == ConstraintType.INEQUALITY:
                v1, v2 = self._get_z3_var(vars[0]), self._get_z3_var(vars[1])
                self.solver.add(v1 != v2)
            
            elif ctype == ConstraintType.EQUALITY:
                v1, v2 = self._get_z3_var(vars[0]), self._get_z3_var(vars[1])
                self.solver.add(v1 == v2)
            
            elif ctype == ConstraintType.LESS_THAN:
                v1, v2 = self._get_z3_var(vars[0]), self._get_z3_var(vars[1])
                self.solver.add(v1 < v2)
            
            elif ctype == ConstraintType.LESS_EQUAL:
                v1, v2 = self._get_z3_var(vars[0]), self._get_z3_var(vars[1])
                self.solver.add(v1 <= v2)
            
            elif ctype == ConstraintType.GREATER_THAN:
                v1, v2 = self._get_z3_var(vars[0]), self._get_z3_var(vars[1])
                self.solver.add(v1 > v2)
            
            elif ctype == ConstraintType.GREATER_EQUAL:
                v1, v2 = self._get_z3_var(vars[0]), self._get_z3_var(vars[1])
                self.solver.add(v1 >= v2)
            
            elif ctype == ConstraintType.FIXED_VALUE:
                v = self._get_z3_var(vars[0])
                self.solver.add(v == params["value"])
            
            elif ctype == ConstraintType.LINEAR_SUM:
                z3_vars = [self._get_z3_var(v) for v in vars]
                coeffs = params["coefficients"]
                total = params["total"]
                relation = params.get("relation", "=")
                
                expr = sum(c * v for c, v in zip(coeffs, z3_vars))
                
                if relation == "=":
                    self.solver.add(expr == total)
                elif relation == "<=":
                    self.solver.add(expr <= total)
                elif relation == "<":
                    self.solver.add(expr < total)
                elif relation == ">=":
                    self.solver.add(expr >= total)
                elif relation == ">":
                    self.solver.add(expr > total)
            
            elif ctype == ConstraintType.PRODUCT:
                v1 = self._get_z3_var(vars[0])
                v2 = self._get_z3_var(vars[1])
                result = self._get_z3_var(vars[2])
                self.solver.add(v1 * v2 == result)

            elif ctype == ConstraintType.ABSOLUTE_VALUE:
                v = self._get_z3_var(vars[0])
                result = self._get_z3_var(vars[1])
                self.solver.add(z3.Abs(v) == result)
            
            elif ctype == ConstraintType.EXACTLY_ONE:
                z3_vars = [self._get_z3_var(v) for v in vars]
                # Exactly one is true
                self.solver.add(z3.PbEq([(v, 1) for v in z3_vars], 1))
            
            elif ctype == ConstraintType.AT_MOST_ONE:
                z3_vars = [self._get_z3_var(v) for v in vars]
                self.solver.add(z3.PbLe([(v, 1) for v in z3_vars], 1))
            
            elif ctype == ConstraintType.AT_LEAST_ONE:
                z3_vars = [self._get_z3_var(v) for v in vars]
                self.solver.add(z3.Or(z3_vars))
            
            elif ctype == ConstraintType.IMPLIES:
                v1, v2 = self._get_z3_var(vars[0]), self._get_z3_var(vars[1])
                self.solver.add(z3.Implies(v1, v2))
            
            elif ctype == ConstraintType.OR:
                z3_vars = [self._get_z3_var(v) for v in vars]
                self.solver.add(z3.Or(z3_vars))
            
            elif ctype == ConstraintType.AND:
                z3_vars = [self._get_z3_var(v) for v in vars]
                self.solver.add(z3.And(z3_vars))
            
            elif ctype == ConstraintType.REIFIED_COMPARISON:
                flag_var = self._get_z3_var(vars[0])
                lhs_var = self._get_z3_var(vars[1])
                rhs_var = self._get_z3_var(vars[2])
                op = params.get('op', 'eq')
                if op == 'eq':
                    self.solver.add(flag_var == (lhs_var == rhs_var))
                elif op == 'lt':
                    self.solver.add(flag_var == (lhs_var < rhs_var))
                elif op == 'gt':
                    self.solver.add(flag_var == (lhs_var > rhs_var))
                elif op == 'lte':
                    self.solver.add(flag_var == (lhs_var <= rhs_var))
                elif op == 'gte':
                    self.solver.add(flag_var == (lhs_var >= rhs_var))
        
        def _encode_raw_clause(self, clause: List[Tuple[Any, Any, bool]]) -> None:
            """Encode raw clause using Z3."""
            literals = []
            for cell, value, positive in clause:
                if cell in self.compiler.variables:
                    z3_var = self.z3_vars[self.compiler.variables[cell].name]
                    if positive:
                        literals.append(z3_var == value)
                    else:
                        literals.append(z3_var != value)
            
            if literals:
                self.solver.add(z3.Or(literals))
        
        def solve(self) -> Tuple[bool, Optional[Dict[str, Any]]]:
            """Solve and return (sat, model)."""
            result = self.solver.check()
            if result == z3.sat:
                model = self.solver.model()
                assignment = {}
                for name, z3_var in self.z3_vars.items():
                    val = model.eval(z3_var)
                    # Convert Z3 value to Python
                    if z3.is_int_value(val):
                        assignment[name] = val.as_long()
                    elif z3.is_true(val):
                        assignment[name] = True
                    elif z3.is_false(val):
                        assignment[name] = False
                    else:
                        assignment[name] = str(val)
                return True, assignment
            else:
                return False, None

except ImportError:
    # Z3 not available - Z3Backend won't be usable
    pass
